# Generated by Django 3.2.7 on 2021-10-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reactions',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
