# Generated by Django 3.2.7 on 2021-10-19 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_profile_reactions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id']},
        ),
    ]
