# Generated by Django 3.2.7 on 2021-10-10 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='BlockPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.blockpost', verbose_name='Parent Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'BlockPost',
                'verbose_name_plural': 'BlockPosts',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='BlockReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('reaction_type', models.IntegerField(choices=[(1, 'Heart'), (2, 'Wow'), (3, 'Funny')], default=1)),
                ('block_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.blockpost', verbose_name='Block Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Reactor')),
            ],
            options={
                'verbose_name': 'Block Reaction',
                'verbose_name_plural': 'Block Reactions',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='BlockCommentReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('reaction_type', models.IntegerField(choices=[(1, 'Heart'), (2, 'Wow'), (3, 'Funny')], default=1)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.blockcomment', verbose_name='Block Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Reactor')),
            ],
            options={
                'verbose_name': 'Comment Reaction',
                'verbose_name_plural': 'Comment Reactions',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='blockcomment',
            name='block_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.blockpost', verbose_name='Block Post'),
        ),
        migrations.AddField(
            model_name='blockcomment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.blockcomment', verbose_name='Block Parent'),
        ),
        migrations.AddField(
            model_name='blockcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Block Comment'),
        ),
        migrations.CreateModel(
            name='BlockCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category_name', models.CharField(max_length=200)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.blockcategory')),
            ],
            options={
                'verbose_name': 'Block Category',
                'verbose_name_plural': 'Block Categories',
                'ordering': ['-id'],
            },
        ),
    ]
