# Generated by Django 3.2.7 on 2021-10-10 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.model_utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Core', '0003_auto_20211010_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockcomment',
            name='reactions',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Block Reactions'),
        ),
        migrations.AlterField(
            model_name='blockcomment',
            name='text',
            field=models.TextField(verbose_name='Block Content'),
        ),
        migrations.AlterField(
            model_name='blockpost',
            name='reactions',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Block Reactions'),
        ),
        migrations.AlterField(
            model_name='blockpost',
            name='text',
            field=models.TextField(verbose_name='Block Content'),
        ),
        migrations.AlterField(
            model_name='blockpostimage',
            name='block_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.blockpost', verbose_name='Block Post'),
        ),
        migrations.AlterField(
            model_name='blockpostimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.model_utils.file_location, verbose_name='Block Post Image'),
        ),
        migrations.AlterField(
            model_name='blockpostimage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Block Post Image Author'),
        ),
    ]
