# Generated by Django 3.2.7 on 2021-10-11 09:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_auto_20211010_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockpostimage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 10, 11, 9, 42, 24, 250794, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blockpostimage',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blockcomment',
            name='block_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.blockpost', verbose_name='Block Post'),
        ),
    ]
