# Generated by Django 3.2.7 on 2021-10-17 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_auto_20211011_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockpost',
            name='block_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.blockcategory'),
        ),
    ]
